# Generated by Django 2.2.4 on 2020-04-18 13:29

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('orders', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
