# Generated by Django 2.2.13 on 2020-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0003_auto_20200610_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='uuid',
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.PositiveIntegerField(default=26362, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='11983', max_length=50),
        ),
    ]
