# Generated by Django 2.2.13 on 2020-06-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0005_auto_20200624_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='86376', max_length=50),
        ),
    ]
